language: node_js  #设置语言

node_js: stable  #设置相应的版本

before_install:
  - npm install yarn -g

install:
  - yarn install

script:
  - yarn build

after_script:
  - echo ${CNAME} > ./build/CNAME
  - cp ./README.md ./build
  - cd build
  - git init
  - git config user.name "travis"  #修改name
  - git config user.email "travis@geekerhua.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - dev  #只监测note分支
